from __future__ import annotations

import json
import os
from typing import Tuple, List, Optional, Type
import torch
import torch.nn as nn
from torch.fx import SymbolicTracer, Node, GraphModule

from leantorch_exporter.schema import (
    ModelSpec,
    LayerSpec,
    TensorSpec,
    LayerType,
    ActivationType,
    ExactRational,
    DomainSpec,
)


class ModelExporter:
    def __init__(self, model: nn.Module, sample_input: torch.Tensor):
        self.model = model.eval()
        self.sample_input = sample_input
        self.traced_graph: Optional[GraphModule] = None

    def trace(self) -> ModelExporter:
        """Traces the PyTorch model execution graph using torch.fx."""
        tracer = SymbolicTracer()
        graph = tracer.trace(self.model)
        self.traced_graph = GraphModule(tracer.root, graph)
        return self

    def _convert_tensor(self, tensor: torch.Tensor) -> TensorSpec:
        """Flattens a PyTorch tensor and converts float elements to exact rationals."""
        shape = list(tensor.shape)
        flat_data = tensor.detach().cpu().flatten().tolist()
        exact_values = [ExactRational.from_float(val) for val in flat_data]
        return TensorSpec(shape=shape, values=exact_values)

    def build_spec(self, model_name: str, domain: Optional[DomainSpec] = None) -> ModelSpec:
        """Constructs the complete ModelSpec from the traced model."""
        if self.traced_graph is None:
            self.trace()

        layers: List[LayerSpec] = []
        input_shape = list(self.sample_input.shape)
        current_shape = input_shape

        # Sequential extraction for linear architectures
        for name, module in self.model.named_modules():
            if isinstance(module, nn.Linear):
                weight_spec = self._convert_tensor(module.weight)
                bias_spec = self._convert_tensor(module.bias) if module.bias is not None else None
                
                out_shape = [current_shape[0], module.out_features] if len(current_shape) == 2 else [module.out_features]
                
                layer_spec = LayerSpec(
                    name=name,
                    layer_type=LayerType.LINEAR,
                    in_shape=current_shape,
                    out_shape=out_shape,
                    weights=weight_spec,
                    bias=bias_spec,
                    activation=ActivationType.IDENTITY,
                )
                layers.append(layer_spec)
                current_shape = out_shape

            elif isinstance(module, (nn.ReLU, nn.LeakyReLU, nn.Tanh, nn.Sigmoid)):
                act_type = ActivationType(module.__class__.__name__)
                if layers and layers[-1].activation == ActivationType.IDENTITY:
                    # Fuse activation into preceding linear layer spec
                    layers[-1].activation = act_type
                else:
                    # Separate activation layer
                    layer_spec = LayerSpec(
                        name=name,
                        layer_type=LayerType.ACTIVATION,
                        in_shape=current_shape,
                        out_shape=current_shape,
                        activation=act_type,
                    )
                    layers.append(layer_spec)

        output_shape = current_shape

        return ModelSpec(
            model_name=model_name,
            input_shape=input_shape,
            output_shape=output_shape,
            layers=layers,
            domain=domain,
            metadata={"pytorch_version": torch.__version__, "exporter": "LeanTorch-Cert-v0.1"},
        )

    def export_json(self, spec: ModelSpec, output_path: str) -> None:
        """Serializes the ModelSpec to a formatted JSON file."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(spec.model_dump_json(indent=2))

    def generate_lean_code(self, spec: ModelSpec) -> str:
        lines = [
            "-- Auto-generated by LeanTorch-Cert Exporter",
            "import LeanTorch.Core.Network",
            "import Mathlib.Data.Real.Basic",
            "",
            "namespace GeneratedModels",
            "",
            f"def {spec.model_name}_input_dim : ℕ := {spec.input_shape[-1]}",
            f"def {spec.model_name}_output_dim : ℕ := {spec.output_shape[-1]}",
            "",
        ]

        # Generate Lean matrix definitions for each layer
        for idx, layer in enumerate(spec.layers):
            if layer.weights is not None:
                w = layer.weights
                lines.append(f"-- Layer {idx}: {layer.name} Weights ({w.shape[0]}x{w.shape[1]})")
                lines.append(f"def {spec.model_name}_layer_{idx}_weights : Matrix (Fin {w.shape[0]}) (Fin {w.shape[1]}) ℝ :=")
                lines.append("  fun i j => match (i.val, j.val) with")
                
                # Unroll matrix weight entries as rationals
                rows, cols = w.shape[0], w.shape[1]
                for r in range(rows):
                    for c in range(cols):
                        val_idx = r * cols + c
                        rational_str = w.values[val_idx].to_lean_string()
                        lines.append(f"  | ({r}, {c}) => {rational_str}")
                lines.append("  | _ => 0")
                lines.append("")

            if layer.bias is not None:
                b = layer.bias
                lines.append(f"-- Layer {idx}: {layer.name} Bias (dim {b.shape[0]})")
                lines.append(f"def {spec.model_name}_layer_{idx}_bias : Fin {b.shape[0]} → ℝ :=")
                lines.append("  fun i => match i.val with")
                for i_val in range(b.shape[0]):
                    rational_str = b.values[i_val].to_lean_string()
                    lines.append(f"  | {i_val} => {rational_str}")
                lines.append("  | _ => 0")
                lines.append("")

        lines.append("end GeneratedModels")
        return "\n".join(lines)

    def export_lean_file(self, spec: ModelSpec, output_path: str) -> None:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        code = self.generate_lean_code(spec)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(code)
